---
title: "Final"
author: "Park si un"
date: '2020 12 13 '
output:
  html_document: default
  pdf_document: default
---

#1. 서울, 경기, 강원 지역의 국립공원 위치를 지도 상에 마커로 표시하되 국립공원의 이름을 함께 표시하시오
```{r}
install.packages("ggmap")
library(ggmap)
register_google(key = 'AIzaSyCTtXx8mu7U1Mpv5q5YMCjygRIxmVc7edA')

names <- c("북한산국립공원","설악산국립공원","오대산국립공원","치악산국립공원","태백산국립공원")
gc <- geocode(enc2utf8(names))
df <- data.frame(name = names, lon = gc$lon, lat = gc$lat) 
cen <- c(mean(df$lon), mean(df$lat))
map <- get_googlemap(center = cen,
                     maptype = 'roadmap',
                     zoom = 8,
                     markers = gc)                
gmap <- ggmap(map)
gmap +                                          
    geom_text(data = df,
              aes(x = lon, y = lat),
              size = 5,
              label = df$name)                    
```

#2. treemap 패키지의 GNI2014 데이터셋을 이용하여 북아메리카(North America) 대륙에 있는 각 나라의 위치에 그 나라의 인구수를 원의 크기로 표시하시오. (원의 색은 초록색, alpha=0.5)
```{r}
install.packages("treemap")
library(treemap)
data(GNI2014)

AME <- GNI2014[GNI2014$continent == 'North America', ]

treemap(AME,
        index = c("continent","iso3"),
        vSize = "population",
        vColor = "GNI",
        type = "value",
        bg.labels = "yellow",
        title = "AME")

install.packages("ggplot2")

ggplot(AME, aes(x=population, y=country)) +
  geom_point(aes(size=population), shape=21, colour="green",
             fill="green", alpha=0.5)

```

#3. 스티브 잡스의 스탠포드 대학 졸업식 연설문에 대해 워드클라우드를 작성하시오. (steve Jobs.txt)
```{r}
install.packages("dplyr")
install.packages("wordcloud2")

library(dplyr) 
library(wordcloud2) 

read.csv("steve Jobs.csv")
top50 = wordDf_TF %>% top_n(50) # top 50 단어추출 


wordcloud2(data = top50 , color = "random-dark" , shape = "cloud" , size = 0.5 , fontFamily = "나눔고딕")

```

#4. 네이버 데이터랩에서 주제어를 '캠핑'과 '텐트'로 하여 최근 1년 간의 검색 트렌드를 확인하되, 25세 이상과 30대 소비자를 대상으로 남성과 여성을 구분하고, 그래프에서 어떤 차이가 발견되는지 설명하시오.
```{r}


```